### PR TITLE
(Fixes #63 and #66) Fix Mime Related Security Issues

### LINKED ISSUE #63: Issue T: Incomplete MIME Type Canonicalization in validate_mime_type
## Location
[crates/mdk-core/src/media_processing/validation.rs#L45](https://github.com/LeastAuthority/marmot-protocol-mdk/blob/5efd9c39a77b87499568ebd49a48f180e528c7ae/crates/mdk-core/src/media_processing/validation.rs#L45)

## Synopsis
The function validate_mime_type performs incomplete canonicalization and returns MIME types with trailing parameters, contrary to MIP-04, which requires stripping parameters.

## Impact
Medium.

An attacker or malformed client input may induce protocol-level mismatches and authentication failures where the canonical MIME type feeds associated data or key derivation, and benign parameters may cause denial of service via false mismatches.

## Feasibility
High.

An attacker can set the mime_type parameter in user-controlled metadata.

## Severity
High.

## Preconditions
For this issue to occur, the following must hold true:

- The attacker must control the mime_type string;
- Downstream components must use the returned value by the validate_mime_type function in AAD, KDF input, or equality checks; and
- Peer implementations or other components must canonicalize per MIP-04 or otherwise strip parameters.

## Technical Details
The function validate_mime_type only trims whitespace and lowercases input, then checks for the presence of "/" and a maximum length. It does not remove parameters after ";". Inputs such as "image/png; charset=utf-8" therefore validate and are returned unchanged aside from case and whitespace, which violates MIP-04 canonicalization semantics that require type/subtype without parameters.

When the function validate_mime_type_matches_data compares the returned canonical_claimed against the value from the function detect_mime_type_from_data, a parameterized claimed type such as "image/png; charset=utf-8" will not equal "image/png" and triggers MediaProcessingError::MimeTypeMismatch. An attacker can exploit this by supplying a parameterized type to cause preventable rejections or to desynchronize AAD or KDF inputs across components that follow MIP-04, producing authentication or decryption failures.

## Remediation
We recommend replacing the normalization in the function validate_mime_type with canonicalization that discards any substring beginning with ";" and returns only type/subtype. In addition, we recommend comparing only this canonical form in validate_mime_type_matches_data, per MIP-04.

## Status
Reported.

### PR DESCRIPTION
**Pull request by dannym-arx**
## Summary by CodeRabbit

* **New Features**
  * Media references and encryption now include an explicit scheme version for consistent upload/download handling.
  * MIME types are canonicalized (parameter stripping, lowercasing) with stricter group-image validation and filename/size checks.

* **Bug Fixes**
  * Stronger MIME allowlist enforcement and byte-level image validation to block spoofed or unsupported uploads.
  * Upload and decryption flows now respect scheme-versioned keys/tags for compatibility and error detection.

* **Tests**
  * Expanded coverage for MIME canonicalization, escape-hatch behavior, spoofing prevention, scheme-version parsing, and validations.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by mubarakcoded — APPROVED** [review]
This is solid security work 🚀

File: crates/mdk-core/src/media_processing/validation.rs [hunk 1]
```diff
@@ -16,6 +16,44 @@ use crate::media_processing::types::{
 #[cfg(feature = "mip04")]
 use crate::media_processing::types::MAX_FILENAME_LENGTH;
 
+/// Supported MIME types for encrypted media upload
+///
+/// This allowlist restricts the types of media that can be encrypted and uploaded,
+/// preventing spoofing and ensuring only supported formats are processed.
+pub(crate) const SUPPORTED_MIME_TYPES: &[&str] = &[
```
Comment (erskingardner) [inline crates/mdk-core/src/media_processing/validation.rs]: So - this is a really interesting one. I had originally added a lot of this exact type of validation and after a bunch of back and forth, @jgmontoya and I agreed that this felt more like an application concern than it did a library concern. 

https://github.com/marmot-protocol/mdk/pull/2#discussion_r2383273818

Unfortunately, we didn't capture the actual conversation in comments... but [here is the commit](https://github.com/marmot-protocol/mdk/pull/2/changes/bfd48499be912470c415fce89e2a84d954d0a4b3) where I removed the code that was doing this. 

@dannym-arx @mubarakcoded would like to hear your thoughts on all of it.

Comment (dannym-arx) [reply crates/mdk-core/src/media_processing/validation.rs]: I wasn't aware of this conversation; but I was following the advice from LA. perhaps we should have two mime type validations, one for things used for group images, which should be handled by MDK, and a separate one for attachments which are to be handled by the users of mdk (such as whitenoise-rs)?

Comment (mubarakcoded) [reply crates/mdk-core/src/media_processing/validation.rs]: I second Danny's approach - splitting by use case makes a lot of sense.

For group images MDK should enforce a strict allowlist. These are protocol-level avatars/icons, so we should restrict to safe image formats only. This is clearly MDK's responsibility.

For encrypted attachments, the allowlist should be optional or configurable. Different apps have different needs - a messaging app might want documents, a file-sharing app might want archives, etc. This should be the application's decision.

Comment (dannym-arx) [reply crates/mdk-core/src/media_processing/validation.rs]: I meant images that we store in the group data extension.

Personally I don't agree that it would be over-engineering, the whole point of MDK is that it's a library separate from whitenoise itself, and that it can be used for any kind of application that need MLS over nostr, and chances are that many of those will need file uploads.

For example what if someone wanted to be build something like nextcloud over nostr? (and by the way, anyone reading this who has the time, please build this lol)

**Review by jgmontoya — APPROVED** [review]
