### PR TITLE
fix: prevent nostr_group_id cache collision and stale key entries in memory storage

### LINKED ISSUE #72: Issue AC: nostr_group_id Cache Collision Leaves Stale Keys and Enables Lookup Hijack
## Location
[mdk-memory-storage/src/groups.rs#L15](https://github.com/LeastAuthority/marmot-protocol-mdk/blob/30bc334c228771d91553b78866b17767804e8275/crates/mdk-memory-storage/src/groups.rs#L15)

## Synopsis
Non-unique caching of groups by nostr_group_id permits overwrites and stale mappings, which causes misrouting and denial of service.

## Impact
Medium.

An attacker who can create or update a group can set nostr_group_id to collide with a victim, hijacking lookups and causing operations to target attacker-controlled or stale groups.

## Feasibility
Medium.

If clients can choose nostr_group_id or trigger saves, collisions are trivial to produce using only standard group-creation privileges.

## Severity
Medium.

## Preconditions
For this issue to occur, the following must hold:

- The application must use find_group_by_nostr_group_id to route or authorize operations;
- The attacker must have the ability to create or update groups with chosen nostr_group_id values; and
- No higher-layer uniqueness enforcement or cleanup on rename should be present.

## Technical Details
The function save_group writes each group into groups_cache keyed by mls_group_id and into groups_by_nostr_id_cache keyed by nostr_group_id. It calls cache.put without uniqueness checks or removal of prior nostr_group_id keys when an identifier changes. This produces last-write-wins overwrites and stale entries. There are also no guards in the mdk-core crate that prevent this issue when mdk-core is run with the memory storage.

A colliding write to groups_by_nostr_id_cache replaces an existing mapping, so find_group_by_nostr_group_id resolves to the most recently saved group. After a rename, the old key persists, so lookups by the old identifier return an incorrect or attacker-controlled state.

## Remediation
We recommend replacing the unguarded cache.put in save_group with a conflict-checked update that rejects saves when the variable nostr_group_id already maps to a different mls_group_id. We also suggest adopting an atomic update that removes any previous nostr_group_id key for the same group before inserting the new one.

## Status
Reported.

### PR DESCRIPTION
**Pull request by mubarakcoded**
Fixes #72

## Problem

The `save_group` function in memory storage wrote to both `groups_cache` (keyed by `mls_group_id`) and `groups_by_nostr_id_cache` (keyed by `nostr_group_id`) without uniqueness checks. This caused:

1. **Lookup hijacking**: An attacker could create a group with a `nostr_group_id` colliding with a victim's group, causing `find_group_by_nostr_group_id` to return the attacker's group
2. **Stale entries**: When a group's `nostr_group_id` changed, the old key persisted in the cache, returning incorrect/stale data

## Solution

- Reject saves when `nostr_group_id` already maps to a different `mls_group_id`
- Remove stale `nostr_group_id` entries when updating a group with a new identifier
- Acquire both cache locks atomically to ensure consistency

## Testing

Added tests for:
- Collision rejection between different groups
- Stale entry cleanup on `nostr_group_id` change
- Same-group updates still allowed

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented collisions between group identifiers that could produce invalid mappings and potential lookup hijacking.
  * Ensure updates to a group's external ID remove stale mappings so lookups remain consistent.

* **Tests**
  * Added tests for collision rejection, stale-ID cleanup on update, and same-group updates.
  * Test helpers now generate unique external IDs per test group.

* **Documentation**
  * Noted a security/audit fix in the changelog.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: crates/mdk-memory-storage/src/groups.rs [hunk 1]
```diff
@@ -13,18 +13,32 @@ use crate::MdkMemoryStorage;
...
+        let mut nostr_id_cache = self.groups_by_nostr_id_cache.write();
+
+        // Check if nostr_group_id is already mapped to a different mls_group_id
+        if let Some(existing_group) = nostr_id_cache.peek(&group.nostr_group_id)
+            && existing_group.mls_group_id != group.mls_group_id
         {
-            let mut cache = self.groups_cache.write();
-            cache.put(group.mls_group_id.clone(), group.clone());
+            return Err(GroupError::InvalidParameters(format!(
+                "nostr_group_id already exists for a different group (mls_group_id: {:?})",
```
Comment (dannym-arx) [inline crates/mdk-memory-storage/src/groups.rs]: let's not log group ids please. Issue #84
